/obj/secure_closet/barber/New()
	..()
	sleep(2)
	new /obj/item/weapon/razor( src )
	new /obj/item/weapon/razor( src )
	new /obj/item/weapon/razor( src )
	new /obj/item/weapon/scissors( src )
	new /obj/item/weapon/scissors( src )
	new /obj/item/weapon/scissors( src )
	new /obj/item/weapon/dye_h( src )
	new /obj/item/weapon/dye_h( src )
	new /obj/item/weapon/dye_h( src )
	new /obj/item/weapon/dye_h( src )
	return
