/obj/secure_closet/ce/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/rank/chief_engineer( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/device/flash( src )
	new /obj/item/weapon/tank/air( src )
	new /obj/item/clothing/glasses/meson( src )
	new /obj/item/clothing/mask/gas( src )
	new /obj/item/clothing/head/helmet/welding( src )
	new /obj/item/clothing/suit/fire( src )
	new /obj/item/weapon/storage/toolbox/mechanical( src )
	new /obj/item/weapon/storage/toolbox/electrical( src )
	new /obj/item/clothing/head/helmet/hardhat( src )
	return