/obj/secure_closet/hor/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/rank/research_director( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/device/flash( src )
	new /obj/item/weapon/hand_tele( src )
	new /obj/item/clothing/mask/gas/emergency( src )
	new /obj/item/clothing/suit/bio_suit( src )
	new /obj/item/weapon/circular_saw( src )
	new /obj/item/weapon/scalpel( src )
	return